# Generated by Django 3.0.6 on 2020-05-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weathersource', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
