# Generated by Django 3.0.6 on 2020-05-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathersource', '0002_auto_20200523_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Please input model title.', max_length=64)),
                ('published', models.BooleanField(verbose_name='Is this test model published.')),
                ('is_demo', models.BooleanField(help_text='Is this a demo test model?')),
            ],
        ),
    ]
