# Generated by Django 3.0.6 on 2020-06-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weathersource', '0003_testmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='is_demo',
            new_name='degrees',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='published',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='title',
        ),
    ]
